import type { airports } from "../schema.js";

type AirportSeed = typeof airports.$inferInsert;

// Money in cents. Lat/lon approximate but in the right place; runway lengths
// and elevations are public data, used as MVP placeholders.
export const airportSeed: AirportSeed[] = [
  // -------------------------------------------------------------------------
  // Maritime Canada
  // -------------------------------------------------------------------------
  {
    icao: "CYHZ",
    name: "Halifax Stanfield International",
    lat: 44.8808,
    lon: -63.5086,
    elevationFt: 477,
    longestRunwayFt: 10500,
    hasPavedRunway: true,
    country: "CA",
    region: "Maritime Canada",
    size: "major",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.1,
    baseLandingFee: 30_000,
    hasFbo: true,
    hasMaintenance: true,
  },
  {
    icao: "CYQM",
    name: "Greater Moncton Roméo LeBlanc International",
    lat: 46.1122,
    lon: -64.6786,
    elevationFt: 232,
    longestRunwayFt: 8000,
    hasPavedRunway: true,
    country: "CA",
    region: "Maritime Canada",
    size: "regional",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.0,
    baseLandingFee: 10_000,
    hasFbo: true,
    hasMaintenance: true,
  },
  {
    icao: "CYQI",
    name: "Yarmouth",
    lat: 43.8269,
    lon: -66.0881,
    elevationFt: 141,
    longestRunwayFt: 5995,
    hasPavedRunway: true,
    country: "CA",
    region: "Maritime Canada",
    size: "regional",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.0,
    baseLandingFee: 8_000,
    hasFbo: true,
    hasMaintenance: false,
  },
  {
    icao: "CYYG",
    name: "Charlottetown",
    lat: 46.29,
    lon: -63.1211,
    elevationFt: 159,
    longestRunwayFt: 7100,
    hasPavedRunway: true,
    country: "CA",
    region: "Maritime Canada",
    size: "regional",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.0,
    baseLandingFee: 10_000,
    hasFbo: true,
    hasMaintenance: false,
  },
  {
    icao: "CYFC",
    name: "Fredericton International",
    lat: 45.8689,
    lon: -66.5372,
    elevationFt: 68,
    longestRunwayFt: 8000,
    hasPavedRunway: true,
    country: "CA",
    region: "Maritime Canada",
    size: "regional",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.0,
    baseLandingFee: 10_000,
    hasFbo: true,
    hasMaintenance: false,
  },
  {
    icao: "CYSJ",
    name: "Saint John",
    lat: 45.3161,
    lon: -65.8903,
    elevationFt: 357,
    longestRunwayFt: 7001,
    hasPavedRunway: true,
    country: "CA",
    region: "Maritime Canada",
    size: "regional",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.0,
    baseLandingFee: 9_000,
    hasFbo: true,
    hasMaintenance: false,
  },
  {
    icao: "CYYR",
    name: "Goose Bay",
    lat: 53.3192,
    lon: -60.4258,
    elevationFt: 160,
    longestRunwayFt: 11051,
    hasPavedRunway: true,
    country: "CA",
    region: "Maritime Canada",
    size: "remote",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.3,
    baseLandingFee: 15_000,
    hasFbo: true,
    hasMaintenance: false,
  },
  {
    icao: "CYDF",
    name: "Deer Lake",
    lat: 49.2108,
    lon: -57.3914,
    elevationFt: 72,
    longestRunwayFt: 8005,
    hasPavedRunway: true,
    country: "CA",
    region: "Maritime Canada",
    size: "regional",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.05,
    baseLandingFee: 8_000,
    hasFbo: true,
    hasMaintenance: false,
  },
  {
    icao: "CYJT",
    name: "Stephenville",
    lat: 48.5444,
    lon: -58.55,
    elevationFt: 84,
    longestRunwayFt: 10000,
    hasPavedRunway: true,
    country: "CA",
    region: "Maritime Canada",
    size: "regional",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.05,
    baseLandingFee: 8_000,
    hasFbo: false,
    hasMaintenance: false,
  },
  {
    icao: "CYYT",
    name: "St. John's International",
    lat: 47.6186,
    lon: -52.7519,
    elevationFt: 461,
    longestRunwayFt: 8500,
    hasPavedRunway: true,
    country: "CA",
    region: "Maritime Canada",
    size: "major",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.1,
    baseLandingFee: 25_000,
    hasFbo: true,
    hasMaintenance: true,
  },
  // CYAW Shearwater is now classified as a heliport in real-world Canadian
  // AIP (fixed-wing runway decommissioned). Kept here as a fixed-wing strip
  // for sim use — adjust if the project decides to follow current real-world.
  {
    icao: "CYAW",
    name: "Shearwater",
    lat: 44.6394,
    lon: -63.5036,
    elevationFt: 167,
    longestRunwayFt: 6900,
    hasPavedRunway: true,
    country: "CA",
    region: "Maritime Canada",
    size: "small",
    hasJetA: true,
    hasAvgas: false,
    baseFuelMultiplier: 0.95,
    baseLandingFee: 4_000,
    hasFbo: false,
    hasMaintenance: false,
  },
  {
    icao: "CYCH",
    name: "Miramichi",
    lat: 47.0078,
    lon: -65.4492,
    elevationFt: 109,
    longestRunwayFt: 10006,
    hasPavedRunway: true,
    country: "CA",
    region: "Maritime Canada",
    size: "small",
    hasJetA: false,
    hasAvgas: true,
    baseFuelMultiplier: 0.9,
    baseLandingFee: 3_000,
    hasFbo: false,
    hasMaintenance: false,
  },
  // CYCX Gagetown is a military heliport in current real-world AIP. Kept as
  // a small fixed-wing field for sim use — adjust if matching current reality.
  {
    icao: "CYCX",
    name: "Gagetown",
    lat: 45.8311,
    lon: -66.4386,
    elevationFt: 165,
    longestRunwayFt: 5500,
    hasPavedRunway: true,
    country: "CA",
    region: "Maritime Canada",
    size: "small",
    hasJetA: true,
    hasAvgas: false,
    baseFuelMultiplier: 0.95,
    baseLandingFee: 3_000,
    hasFbo: false,
    hasMaintenance: false,
  },
  {
    icao: "CYCL",
    name: "Charlo",
    lat: 47.9908,
    lon: -66.3303,
    elevationFt: 132,
    longestRunwayFt: 6000,
    hasPavedRunway: true,
    country: "CA",
    region: "Maritime Canada",
    size: "small",
    hasJetA: false,
    hasAvgas: true,
    baseFuelMultiplier: 0.9,
    baseLandingFee: 2_500,
    hasFbo: false,
    hasMaintenance: false,
  },

  // -------------------------------------------------------------------------
  // Quebec
  // -------------------------------------------------------------------------
  {
    icao: "CYUL",
    name: "Montréal-Pierre Elliott Trudeau International",
    lat: 45.4706,
    lon: -73.7408,
    elevationFt: 117,
    longestRunwayFt: 11000,
    hasPavedRunway: true,
    country: "CA",
    region: "Quebec",
    size: "major",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.1,
    baseLandingFee: 40_000,
    hasFbo: true,
    hasMaintenance: true,
  },
  {
    icao: "CYQB",
    name: "Québec City Jean Lesage International",
    lat: 46.7911,
    lon: -71.3933,
    elevationFt: 244,
    longestRunwayFt: 9000,
    hasPavedRunway: true,
    country: "CA",
    region: "Quebec",
    size: "regional",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.0,
    baseLandingFee: 12_000,
    hasFbo: true,
    hasMaintenance: true,
  },
  {
    icao: "CYZV",
    name: "Sept-Îles",
    lat: 50.2233,
    lon: -66.2656,
    elevationFt: 180,
    longestRunwayFt: 7000,
    hasPavedRunway: true,
    country: "CA",
    region: "Quebec",
    size: "regional",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.05,
    baseLandingFee: 9_000,
    hasFbo: true,
    hasMaintenance: false,
  },

  // -------------------------------------------------------------------------
  // New England (USA)
  // -------------------------------------------------------------------------
  {
    icao: "KBOS",
    name: "Boston Logan International",
    lat: 42.3656,
    lon: -71.0096,
    elevationFt: 20,
    longestRunwayFt: 10083,
    hasPavedRunway: true,
    country: "US",
    region: "New England",
    size: "major",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.1,
    baseLandingFee: 50_000,
    hasFbo: true,
    hasMaintenance: true,
  },
  {
    icao: "KBGR",
    name: "Bangor International",
    lat: 44.8074,
    lon: -68.8281,
    elevationFt: 192,
    longestRunwayFt: 11440,
    hasPavedRunway: true,
    country: "US",
    region: "New England",
    size: "regional",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.0,
    baseLandingFee: 12_000,
    hasFbo: true,
    hasMaintenance: true,
  },
  {
    icao: "KPWM",
    name: "Portland International Jetport",
    lat: 43.6462,
    lon: -70.3093,
    elevationFt: 76,
    longestRunwayFt: 7200,
    hasPavedRunway: true,
    country: "US",
    region: "New England",
    size: "regional",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.0,
    baseLandingFee: 11_000,
    hasFbo: true,
    hasMaintenance: true,
  },
  {
    icao: "KBHB",
    name: "Hancock County–Bar Harbor",
    lat: 44.45,
    lon: -68.3617,
    elevationFt: 83,
    longestRunwayFt: 5200,
    hasPavedRunway: true,
    country: "US",
    region: "New England",
    size: "small",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 0.95,
    baseLandingFee: 4_000,
    hasFbo: true,
    hasMaintenance: false,
  },
  {
    icao: "KAUG",
    name: "Augusta State",
    lat: 44.3206,
    lon: -69.7973,
    elevationFt: 352,
    longestRunwayFt: 5001,
    hasPavedRunway: true,
    country: "US",
    region: "New England",
    size: "small",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 0.9,
    baseLandingFee: 3_500,
    hasFbo: false,
    hasMaintenance: false,
  },
  {
    icao: "KBDL",
    name: "Bradley International",
    lat: 41.9389,
    lon: -72.6831,
    elevationFt: 173,
    longestRunwayFt: 9510,
    hasPavedRunway: true,
    country: "US",
    region: "New England",
    size: "regional",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.0,
    baseLandingFee: 13_000,
    hasFbo: true,
    hasMaintenance: true,
  },
  {
    icao: "KBTV",
    name: "Burlington International",
    lat: 44.4719,
    lon: -73.1533,
    elevationFt: 335,
    longestRunwayFt: 8320,
    hasPavedRunway: true,
    country: "US",
    region: "New England",
    size: "regional",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.0,
    baseLandingFee: 11_000,
    hasFbo: true,
    hasMaintenance: false,
  },
  {
    icao: "KMHT",
    name: "Manchester–Boston Regional",
    lat: 42.9326,
    lon: -71.4356,
    elevationFt: 266,
    longestRunwayFt: 9250,
    hasPavedRunway: true,
    country: "US",
    region: "New England",
    size: "regional",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.0,
    baseLandingFee: 11_000,
    hasFbo: true,
    hasMaintenance: false,
  },
  {
    icao: "KPVD",
    name: "Rhode Island T. F. Green International",
    lat: 41.7325,
    lon: -71.4204,
    elevationFt: 55,
    longestRunwayFt: 8700,
    hasPavedRunway: true,
    country: "US",
    region: "New England",
    size: "regional",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.0,
    baseLandingFee: 12_000,
    hasFbo: true,
    hasMaintenance: false,
  },
  {
    icao: "KFMH",
    name: "Cape Cod Coast Guard Air Station",
    lat: 41.6586,
    lon: -70.5214,
    elevationFt: 131,
    longestRunwayFt: 9501,
    hasPavedRunway: true,
    country: "US",
    region: "New England",
    size: "small",
    hasJetA: true,
    hasAvgas: false,
    baseFuelMultiplier: 0.95,
    baseLandingFee: 3_000,
    hasFbo: false,
    hasMaintenance: false,
  },
  {
    icao: "KPVC",
    name: "Provincetown Municipal",
    lat: 42.0719,
    lon: -70.2214,
    elevationFt: 9,
    longestRunwayFt: 3502,
    hasPavedRunway: true,
    country: "US",
    region: "New England",
    size: "small",
    hasJetA: false,
    hasAvgas: true,
    baseFuelMultiplier: 0.9,
    baseLandingFee: 2_500,
    hasFbo: false,
    hasMaintenance: false,
  },
  {
    icao: "KMVY",
    name: "Martha's Vineyard",
    lat: 41.3931,
    lon: -70.6143,
    elevationFt: 67,
    longestRunwayFt: 5500,
    hasPavedRunway: true,
    country: "US",
    region: "New England",
    size: "small",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 0.95,
    baseLandingFee: 4_000,
    hasFbo: true,
    hasMaintenance: false,
  },
  {
    icao: "KACK",
    name: "Nantucket Memorial",
    lat: 41.2531,
    lon: -70.06,
    elevationFt: 47,
    longestRunwayFt: 6303,
    hasPavedRunway: true,
    country: "US",
    region: "New England",
    size: "regional",
    hasJetA: true,
    hasAvgas: true,
    baseFuelMultiplier: 1.05,
    baseLandingFee: 9_000,
    hasFbo: true,
    hasMaintenance: false,
  },
];
